### ISSUE TITLE
Allow for project to add its twitter handle 

### ISSUE THREAD

**Issue by rabbah** [rajatjindal/goodfirstissue#15]
When the app tweets out a new issue, it would be useful I think to include a mention of the project by its twitter handle. This would allow the project to retweet and raise the number of twitter impressions. 

This is a neat GitHub app. 👍

**Comment by rajatjindal** [comment]
Hi @rabbah 

Thanks for reporting the issue and thanks for appreciating the app.

I had thought about it, and was wondering what will be the source of twitter handle?

do we have a reliable way of getting twitter handle for a project dynamically. One way could be to manage a static file with repo to twitter handle mapping in the repo and use that.

Thanks
Rajat Jindal

**Comment by rajatjindal** [comment]
I've added some changes for it. may not be perfect, but works. thanks for reporting it.

I saw you enabled and then disabled it for openwhisk. Let me know what else can we do to have you and your projects onboard :)

**Comment by rajatjindal** [comment]
fixed by #16 and #17

**Comment by rabbah** [comment]
the openwhisk repo is now owned by the Apache foundation (a separate GitHub org) and I’ll need to get an maintenance request to add the app. I was doing a quick test to see what it’s like to use the app. Installation was easy :)

It does the raise a question - for an org with a lot of repos, can the monitoring and twitter handle be scoped to a specific repo?
