### ISSUE TITLE
one test issue for bluesky

### ISSUE THREAD

**Issue by rajatjindal** [rajatjindal/goodfirstissue#42]

**Comment by ivedantmistry** [comment]
Hello I'm new to open source contribution, can i take this issue?
Regards.

**Comment by rajatjindal** [comment]
Hi @vedantmistryy, thank you for your interest in contributing to this issue. actually this is a test issue which I am using to test the functionality of the bot and not exactly an issue to fix.

you can follow twitter account: https://twitter.com/goodfirstissue for some good first issues. 

thank you
